services:
    streamlit:
        build:
            dockerfile: ./Dockerfile
            context: ./
        ports:
            - "8081:8501"
        env_file:
            - .env            
